# Generated by Django 3.0.2 on 2020-02-01 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=30)),
                ('class_id', models.CharField(max_length=36)),
                ('assignment_name', models.CharField(max_length=36)),
                ('tek_choice', models.CharField(choices=[('g1', 'Group 1'), ('g2', 'Group 2'), ('g3', 'Group 3')], default='g1', max_length=2)),
                ('grade', models.IntegerField(default=0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
