# Generated by Django 3.0.2 on 2020-01-30 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.Student'),
        ),
    ]
