# Generated by Django 3.0.2 on 2020-01-30 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20200130_1651'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grade',
            old_name='student_id',
            new_name='student',
        ),
    ]
