# Generated by Django 3.0.2 on 2020-01-30 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20200130_1655'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grade',
            old_name='assignment_id',
            new_name='assignment_name',
        ),
    ]
